#!/bin/bash
#PBS -q bigmem
#PBS -l nodes=1:ppn=24
#PBS -l walltime=12:00:00
#PBS -N krakenDB  
#PBS -o kraken.out
#PBS -j oe
#PBS -A loni_selu_gt
#PBS -m abe
#PBS -M april.wright@selu.edu   


#### module load gcc
##module unload mvapich2/2.0/INTEL-14.0.2
##module load openmpi/1.8.1/INTEL-14.0.2

datapath=/work/amwright/kraken
cd $datapath
./kraken-build --standard --threads 24 --db kraken_large
./kraken-build --db kraken_large --clean


